services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-dev
    volumes:
      - ./api-gateway:/workspace:cached
    stdin_open: true
    tty: true
    command: sleep infinity
    ports:
      - "4004:4004"
    networks:
      - internal

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service-dev
    volumes:
      - ./analytics-service:/workspace:cached
    stdin_open: true
    tty: true
    command: sleep infinity
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "4002:4002"
    depends_on:
      kafka:
        condition: service_started
    networks:
      - internal

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: patient-service-dev
    volumes:
      - ./patient-service:/workspace:cached
    command: sleep infinity
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      # SPRING_GRPC_CLIENT_BILLING_SERVICE_ADDRESS: billing-service
      # SPRING_GRPC_CLIENT_BILLING_SERVICE_GRPC_PORT: 9001
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "4000:4000"
    depends_on:
      patient-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - internal

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service-dev
    volumes:
      - ./billing-service:/workspace:cached
    stdin_open: true
    tty: true
    command: sleep infinity
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - "4001:4001"
      - "9001:9001"
    depends_on:
      patient-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - internal

  patient-db:
    image: postgres:latest
    container_name: patient-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - C:\Users\HP\db_volumes\patient-service-db:/var/lib/postgresql
    ports:
      - "5000:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    environment:
      # Node and Role Configuration
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: 'broker,controller'
       # Listener Configuration
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      # Controller Configuration
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Cluster ID (required for KRaft mode)
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      # Replication factors for single-node setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - C:\Users\HP\db_volumes\kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres-data: